Updated the Readme Doc
vicradon/anon-msg-app pull request #1
Opened 2022-12-28 21:47 UTC by Devbysteph

I improved the Readmen doc, please review it.

2022-12-28 22:12 UTC, vicradon requested changes

2022-12-28 22:12 UTC, vicradon commented on README.md
> +## Download
Might want to replace this download with "View". You know it's a web app.

2022-12-28 22:12 UTC, vicradon commented on README.md
> +## App Screenshots
I think we can add this now. Both the desktop and mobile version.

2022-12-28 22:12 UTC, vicradon commented on README.md
> +>We are continually improving the platform, to make AnonMsg🙈 as user-friendly as possible.To get started right now, all you need to do is to go [AnonMsg🙈](https://anon-msg-app.vercel.app/)and enter y
Might want to replace the phrase "end to end" encryption with: "aes cipher".

2022-12-28 22:12 UTC, vicradon commented on README.md
> +<img src="./public/Emoji.png" style: width="100px">
This image is broken... I think it has to do with the relative link. Try removing the `./public`.

2022-12-28 22:15 UTC, Devbysteph commented on README.md
> +## Download
Okayy sure

2022-12-28 22:15 UTC, Devbysteph commented on README.md
> +## App Screenshots
Alright, noted. Is is responsive now?

2022-12-28 22:17 UTC, Devbysteph commented on README.md
> +<img src="./public/Emoji.png" style: width="100px">
Alright, the saved the image on the public folder that was why I referenced it. What do you think. I will look into you ASAP.

2022-12-28 22:17 UTC, Devbysteph commented on README.md
> +>We are continually improving the platform, to make AnonMsg🙈 as user-friendly as possible.To get started right now, all you need to do is to go [AnonMsg🙈](https://anon-msg-app.vercel.app/)and enter y
Okay, Roger that.

2022-12-29 15:20 UTC, vicradon requested changes

2022-12-29 15:20 UTC, vicradon commented on README.md
> +![Logoplaceholder](https://github.com/Devbysteph/anon-msg-app/blob/main/public/Logo%20placeholder.png)
Can you also structure this image like the others? If it references your repo, it might not show if your repo is moved.

2022-12-29 16:07 UTC, Devbysteph commented on README.md
> +![Logoplaceholder](https://github.com/Devbysteph/anon-msg-app/blob/main/public/Logo%20placeholder.png)
I've made modifications to them, thank you for pointing it out.

2022-12-29 17:05 UTC, vicradon approved these changes

2022-12-29 17:08 UTC, vicradon commented
Thanksyou @Devbysteph for this contribution.

2022-12-29 17:08 UTC, merged